export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div className="flex h-full items-center justify-center">
            {children}
        </div>
    );
}
